sudo: false
language: php
notifications:
  email:
    on_success: never
    on_failure: change
branches:
  only:
    - master
    - "/^v?[0-9\\.]+/"
php:
- 7.0
- 5.6
env:
- WP_VERSION=nightly WP_MULTISITE=0
- WP_VERSION=latest WP_MULTISITE=0
after_success:
- sed -i -e "s/nightly/${TRAVIS_TAG}/" speech-shortcode.php
- curl https://raw.githubusercontent.com/miya0001/auto-build/master/auto-build.sh
  | bash
before_script:
- bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
- composer install
- npm install
- npm run build
script:
- vendor/bin/phpunit
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: fc60/yUNFkFM43MFkBKrBAtdZaz0LMGtPtmkR3d0S5zcM/LLVbQlU4IlubTmhM5QX+3pa8Q7QsccDHmB83ySIA5+sckPrtuz7UsP5/EsjLfbT0b+g4Xhzw3n5z71sOseNK6INXTnBBhfT3KhSiMwvCjv7EjkshWFTPxvdwHpVBtlSZGwVRP7qhLtd1K39zqQDKK9QvvTLY96/x5JWK8cIqaSIOpIY/tPsaZw3wsZ+9U5+Qnn+Lumn6ctPcfYe+Jtvny7mGkseVFNZNIVa51X+Oa9AvrOICaTOAK25vV/lSAzkXqx7DYycQeE1o/Iyfx8Nfl2wXJRH5iMF1hxUuieVByaWc52E63LBRe/ml3jiWUPheGY2wKeaBZPWRUNuONzcn9vXsjIU8ed61u4NzP6bpz7h8AxnTnJjNKkyd6UdDmUuoAMrztk3iCDouyTJ38HwGku3Io154iu74e5X6WnzCOKWG4YxAR5nGhBaJweKiMqkUjLam0SMGC69at8aGPnLuT+f2+czy0cQfRfWnYn2wLaoRz2UtSeLc8H9ak49oMhanUBeDW/eGVb2ubriWAAxNLmuyLATVksBVCIZdVGz24DWW6v68b2JKJ/+xtrI7HikL6Kj+gSg3lZcBizUuFgiGzlxaigIbBDgD/lSXYtsmo8YRZ5E4kq1ul5M39SMK0=
  file: speech-shortcode.zip
  on:
    tags: true
    repo: miya0001/speech-shortcode
